version: '3'

services:

  proxy:
    container_name: proxy
    entrypoint: dockerize -wait tcp://app:3000 -timeout 60s /bin/sh -c "nginx -g 'daemon off;'"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - node-network
    tty: true
    ports:
      - 8080:80
    depends_on: 
      - app
      - db
    restart: always

  app: 
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    restart: always

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge